# Generated by Django 2.0.3 on 2018-07-19 05:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180719_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepost',
            options={'ordering': ('-updated_data',)},
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created_data',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 19, 5, 10, 13, 296055, tzinfo=utc)),
        ),
    ]
